### PR TITLE
Gracefully handle pull requests without bodies

### LINKED ISSUE #503: `repo_and_version_of_pull_request_body` crashes if there is a PR with empty body
`repo_and_version_of_pull_request_body` crashes if there is a PR with empty body.

```
ERROR: MethodError: no method matching occursin(::String, ::Nothing)
Closest candidates are:
  occursin(::Union{AbstractChar, AbstractString}, ::AbstractString) at strings/search.jl:628
  occursin(::Any) at strings/search.jl:642
Stacktrace:
 [1] repo_and_version_of_pull_request_body(body::Nothing)
   @ RegistryCI.TagBot ~/.julia/packages/RegistryCI/3KBMb/src/TagBot/TagBot.jl:48
 [2] #1
   @ ~/.julia/packages/RegistryCI/3KBMb/src/TagBot/cron.jl:5 [inlined]
 [3] iterate
   @ ./generator.jl:47 [inlined]
 [4] _collect(c::Vector{GitHub.PullRequest}, itr::Base.Generator{Vector{GitHub.PullRequest}, RegistryCI.TagBot.var"#1#3"}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
   @ Base ./array.jl:807
 [5] collect_similar
   @ ./array.jl:716 [inlined]
 [6] map
   @ ./abstractarray.jl:2933 [inlined]
 [7] handle_cron(event::Dict{String, Any})
   @ RegistryCI.TagBot ~/.julia/packages/RegistryCI/3KBMb/src/TagBot/cron.jl:5
 [8] main()
   @ RegistryCI.TagBot ~/.julia/packages/RegistryCI/3KBMb/src/TagBot/TagBot.jl:43
 [9] top-level scope
   @ none:1
Error: Process completed with exit code 1.
```

After editing the body of the responsible PR, the error disappears.

### PR DESCRIPTION
**Pull request by bauglir**
Calling `repo_and_version_of_pull_request_body` with an empty body causes errors due to `occursin` not handling `Nothing` values.

```julia
ERROR: MethodError: no method matching occursin(::String, ::Nothing)
Closest candidates are:
  occursin(::Union{AbstractChar, AbstractString}, ::AbstractString) at strings/search.jl:628
  occursin(::Any) at strings/search.jl:642
Stacktrace:
 [1] repo_and_version_of_pull_request_body(body::Nothing)
   @ RegistryCI.TagBot ~/.julia/packages/RegistryCI/3KBMb/src/TagBot/TagBot.jl:48
```

This could be handled using a separate dispatch, but this approach seems more in line with the rest of the codebase. Just let me know if you'd prefer the dispatch implementation instead and I'll get this updated.

Fixes #503.

### CODE REVIEW

File: test/tagbot-unit.jl [hunk 1]
```diff
@@ -36,6 +36,8 @@ end
     @test TB.repo_and_version_of_pull_request_body(ssh) == ("Foo/Bar", "v1.2.3")
     gitlab = body("https://gitlab.com/Foo/Bar")
     @test TB.repo_and_version_of_pull_request_body(gitlab) == (nothing, "v1.2.3")
+    nobody = nothing
```
Comment (DilumAluthge) [inline test/tagbot-unit.jl:39]:
```suggestion
no_body = nothing
```

File: src/TagBot/TagBot.jl [hunk 2]
```diff
@@ -45,6 +45,7 @@ function main()
 end
 
 function repo_and_version_of_pull_request_body(body)
+    isnothing(body) && return (nothing, nothing)
```
Comment (DilumAluthge) [inline src/TagBot/TagBot.jl:48]: Can you add a brief comment explaining when we hit this code path (i.e. we hit this code path if the PR body is empty).

**Review by DilumAluthge — COMMENTED** [review]
A few small comments, but otherwise LGTM.

File: test/tagbot-unit.jl (hunk 1 above)
Comment (bauglir) [reply test/tagbot-unit.jl]: Fixed in 3fbe6e210c591c01596de92d6911f7a86c9eda97.

File: src/TagBot/TagBot.jl (hunk 2 above)
Comment (bauglir) [reply src/TagBot/TagBot.jl:50]: I had been going back and forth on that and ended up removing it in the end 😅 Added back in 3fbe6e210c591c01596de92d6911f7a86c9eda97.

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
Thanks Joris!

**Comment by DilumAluthge** [comment]
bors merge
